import Head from 'next/head';
import Link from 'next/link';
import { NavWrapper } from '../components/navigation';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Reddit</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <NavWrapper>
        <>
          <Link href='/1'>
            <a> first </a>
          </Link>
          <Link href='/2'>
            <a> second </a>
          </Link>
        </>
      </NavWrapper>
    </div>
  );
}
